import { useMemo, useState } from "react";
import { useInfiniteQuery, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { useCrmWorkspace } from "../../crm.module.tsx";
import type { CrmTableFilters, CrmTableItem, CrmTag, RelationshipStatus } from "../../domain/entities/crm-workspace.ts";

const relationshipLabel: Record<RelationshipStatus, string> = { new: "Novo", recurring: "Recorrente", vip: "VIP" };
const relationshipClass: Record<RelationshipStatus, string> = { new: "bg-sky-50 text-sky-700", recurring: "bg-emerald-50 text-emerald-700", vip: "bg-violet-50 text-violet-700" };
const formatDate = (value: string | null, withTime = false) => value ? new Intl.DateTimeFormat("pt-PT", { day: "2-digit", month: "short", year: "numeric", ...(withTime ? { hour: "2-digit", minute: "2-digit" } : {}) }).format(new Date(value.length === 10 ? `${value}T12:00:00Z` : value)) : "—";

function StatusBadges({ item }: { item: CrmTableItem }) {
  return <div className="flex flex-wrap gap-1"><span className={`rounded-full px-2.5 py-0.5 text-xs font-medium ${relationshipClass[item.status.relationship]}`}>{relationshipLabel[item.status.relationship]}</span>{item.status.inactive && <span className="rounded-full bg-stone-100 px-2.5 py-0.5 text-xs font-medium text-stone-600">Inativo</span>}</div>;
}

function SortableHeader({ label, active, direction, onClick, sticky }: { label: string; active: boolean; direction?: "asc" | "desc"; onClick: () => void; sticky?: boolean }) {
  return <th aria-sort={active ? (direction === "asc" ? "ascending" : "descending") : "none"} className={`${sticky ? "sticky left-12 z-30 bg-stone-50/95" : ""} px-3 py-3 text-left text-xs font-semibold uppercase tracking-wide text-stone-500`}><button type="button" onClick={onClick} className="group flex items-center gap-1.5 whitespace-nowrap text-left hover:text-stone-800"><span>{label}</span><span className={`text-sm ${active ? "text-[#ED5C32]" : "text-stone-300 group-hover:text-stone-400"}`}>{active ? (direction === "asc" ? "↑" : "↓") : "↕"}</span></button></th>;
}

function ActionModal({ customerIds, onClose }: { customerIds: string[]; onClose: () => void }) {
  const service = useCrmWorkspace(); const qc = useQueryClient();
  const { data: types = [] } = useQuery({ queryKey: ["crm-workspace", "action-types"], queryFn: service.listActionTypes });
  const [type, setType] = useState(""); const [creatingType, setCreatingType] = useState(false);
  const [newTypeName, setNewTypeName] = useState(""); const [newTypeColor, setNewTypeColor] = useState("#64748b");
  const [editingType, setEditingType] = useState(false); const [editedTypeName, setEditedTypeName] = useState("");
  const [date, setDate] = useState(""); const [notes, setNotes] = useState("");
  const mutation = useMutation({ mutationFn: service.createActions, onSuccess: async () => { await qc.invalidateQueries({ queryKey: ["crm-workspace"] }); onClose(); } });
  const typeMutation = useMutation({ mutationFn: service.createActionType, onSuccess: async (created) => { setType(created.code); setCreatingType(false); setNewTypeName(""); await qc.invalidateQueries({ queryKey: ["crm-workspace", "action-types"] }); } });
  const editTypeMutation = useMutation({ mutationFn: ({ code, name }: { code: string; name: string }) => service.updateActionType(code, { name }), onSuccess: async () => { setEditingType(false); await qc.invalidateQueries({ queryKey: ["crm-workspace"] }); } });
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!type || !date) return; mutation.mutate({ customerIds, actionTypeCode: type,
    scheduledFor: new Date(date).toISOString(), notes: notes.trim() || null, scriptCode: null }); };
  return <Modal title={`Agendar ação · ${customerIds.length} cliente(s)`} onClose={onClose}>
    <form onSubmit={submit} className="space-y-4">
      <Field label="Tipo de ação"><select value={type} onChange={(e) => { setEditingType(false); if (e.target.value === "__create__") { setCreatingType(true); setType(""); } else { setCreatingType(false); setType(e.target.value); } }} className="input"><option value="">Selecionar…</option>{types.filter((item) => item.active).map((item) => <option key={item.code} value={item.code}>{item.name}</option>)}<option value="__create__">＋ Criar tipo de ação</option></select>{type && !editingType && <button type="button" onClick={() => { setEditedTypeName(types.find((item) => item.code === type)?.name ?? ""); setEditingType(true); }} className="mt-1.5 text-xs font-medium text-stone-500 underline hover:text-[#ED5C32]">Editar label deste tipo</button>}</Field>
      {editingType && type && <div className="rounded-lg border border-[#F5C992]/60 bg-[#FDF8F5] p-3"><p className="mb-2 text-sm font-medium text-stone-700">Editar label</p><input autoFocus value={editedTypeName} onChange={(e) => setEditedTypeName(e.target.value)} className="input" />{editTypeMutation.isError && <p className="mt-2 text-xs text-red-600">{editTypeMutation.error.message}</p>}<div className="mt-3 flex justify-end gap-2"><button type="button" onClick={() => setEditingType(false)} className="btn-secondary">Cancelar</button><button type="button" disabled={!editedTypeName.trim() || editTypeMutation.isPending} onClick={() => editTypeMutation.mutate({ code: type, name: editedTypeName.trim() })} className="btn-primary">Guardar label</button></div></div>}
      {creatingType && <div className="rounded-lg border border-[#F5C992]/60 bg-[#FDF8F5] p-3"><p className="mb-3 text-sm font-medium text-stone-700">Novo tipo de ação</p><div className="grid grid-cols-[1fr_48px] gap-2"><input autoFocus placeholder="Ex.: Pedir feedback" value={newTypeName} onChange={(e) => setNewTypeName(e.target.value)} className="input" /><input aria-label="Cor do tipo de ação" type="color" value={newTypeColor} onChange={(e) => setNewTypeColor(e.target.value)} className="h-10 w-12 rounded-md border border-stone-300 p-1" /></div>{typeMutation.isError && <p className="mt-2 text-xs text-red-600">{typeMutation.error.message}</p>}<div className="mt-3 flex justify-end gap-2"><button type="button" onClick={() => setCreatingType(false)} className="btn-secondary">Cancelar</button><button type="button" disabled={!newTypeName.trim() || typeMutation.isPending} onClick={() => typeMutation.mutate({ name: newTypeName.trim(), color: newTypeColor })} className="btn-primary">Criar e selecionar</button></div></div>}
      <Field label="Data de follow-up"><input required type="datetime-local" value={date} onChange={(e) => setDate(e.target.value)} className="input" /></Field>
      <Field label="Notas"><textarea rows={3} value={notes} onChange={(e) => setNotes(e.target.value)} className="input resize-none" /></Field>
      {mutation.isError && <p className="text-sm text-red-600">{mutation.error.message}</p>}
      <div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="btn-secondary">Cancelar</button><button disabled={mutation.isPending || !type || !date || creatingType || editingType} className="btn-primary">{mutation.isPending ? "A guardar…" : "Agendar ação"}</button></div>
    </form>
  </Modal>;
}

function toDateTimeLocal(value: string): string {
  const date = new Date(value); const pad = (part: number) => String(part).padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;
}

function CompleteActionModal({ items, onClose }: { items: CrmTableItem[]; onClose: () => void }) {
  const service = useCrmWorkspace(); const qc = useQueryClient(); const actionable = items.filter((item) => item.nextAction !== null);
  const [completedAt, setCompletedAt] = useState<Record<string, string>>(() => Object.fromEntries(actionable.map((item) => [item.nextAction!.id, toDateTimeLocal(item.nextAction!.scheduledFor)])));
  const mutation = useMutation({ mutationFn: () => service.completeActions(actionable.map((item) => ({ id: item.nextAction!.id, completedAt: new Date(completedAt[item.nextAction!.id]!).toISOString() }))), onSuccess: async () => { await qc.invalidateQueries({ queryKey: ["crm-workspace"] }); onClose(); } });
  const valid = actionable.length > 0 && actionable.every((item) => Boolean(completedAt[item.nextAction!.id]));
  return <Modal title={`Concluir próxima ação · ${actionable.length} cliente(s)`} onClose={onClose}><div className="space-y-4"><div className="max-h-[55vh] space-y-3 overflow-y-auto pr-1">{actionable.map((item) => { const action = item.nextAction!; return <div key={action.id} className="rounded-lg border border-stone-200 bg-stone-50 p-3"><div className="mb-3"><p className="font-medium text-stone-900">{action.typeName}</p><p className="text-sm text-stone-500">{item.fullName}</p>{action.notes && <p className="mt-1 text-sm text-stone-600">{action.notes}</p>}</div><Field label="Data e hora de conclusão"><input required type="datetime-local" value={completedAt[action.id] ?? ""} onChange={(event) => setCompletedAt((current) => ({ ...current, [action.id]: event.target.value }))} className="input" /></Field></div>; })}</div><p className="text-xs text-stone-500">Ao confirmar, cada ação passará para “Última ação” e a próxima ação ficará livre.</p>{mutation.isError && <p className="text-sm text-red-600">{mutation.error.message}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="btn-secondary">Cancelar</button><button type="button" disabled={!valid || mutation.isPending} onClick={() => mutation.mutate()} className="btn-primary">{mutation.isPending ? "A concluir…" : `Confirmar ${actionable.length} ação(ões)`}</button></div></div></Modal>;
}

function ActionHistoryModal({ item, onClose, onSchedule }: { item: CrmTableItem; onClose: () => void; onSchedule: () => void }) {
  const service = useCrmWorkspace();
  const query = useInfiniteQuery({ queryKey: ["crm-workspace", "action-history", item.id],
    queryFn: ({ pageParam }) => service.listCustomerActions(item.id, pageParam), initialPageParam: undefined as string | undefined,
    getNextPageParam: (lastPage) => lastPage.nextCursor ?? undefined });
  const pending = query.data?.pages[0]?.pending ?? null;
  const history = query.data?.pages.flatMap((page) => page.history) ?? [];
  const total = query.data?.pages[0]?.total ?? 0;
  return <Modal title={`Histórico de ações · ${item.fullName}`} onClose={onClose}><div className="max-h-[70vh] space-y-5 overflow-y-auto pr-1">
    {query.isLoading && <div className="py-8 text-center text-sm text-stone-500">A carregar histórico…</div>}
    {query.isError && <div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{query.error.message}</div>}
    {!query.isLoading && <><section><div className="mb-2 flex items-center justify-between"><h3 className="text-xs font-semibold uppercase tracking-wide text-stone-400">Próxima ação</h3>{!pending && <button onClick={onSchedule} className="text-xs font-medium text-[#ED5C32] hover:underline">+ Agendar ação</button>}</div>{pending ? <div className="rounded-lg border border-[#F5C992]/60 bg-[#FDF8F5] p-4"><div className="flex items-start gap-3"><span style={{ backgroundColor: pending.actionTypeColor }} className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full" /><div><p className="font-medium text-stone-900">{pending.actionTypeName}</p><p className="mt-1 text-sm text-stone-600">Agendada para {formatDate(pending.scheduledFor, true)}</p>{pending.notes && <p className="mt-2 text-sm text-stone-600">{pending.notes}</p>}</div></div></div> : <div className="rounded-lg border border-dashed border-stone-200 p-4 text-sm text-stone-400">Nenhuma próxima ação agendada.</div>}</section>
    <section><div className="mb-3 flex items-center justify-between"><h3 className="text-xs font-semibold uppercase tracking-wide text-stone-400">Histórico</h3><span className="text-xs text-stone-400">{total} ação(ões)</span></div>{history.length === 0 ? <div className="rounded-lg border border-dashed border-stone-200 p-5 text-center text-sm text-stone-400">Ainda não existem ações concluídas.</div> : <ol className="relative ml-1 border-l border-stone-200">{history.map((action) => <li key={action.id} className="relative ml-5 pb-5 last:pb-0"><span style={{ backgroundColor: action.actionTypeColor }} className="absolute -left-[25px] top-1 h-2.5 w-2.5 rounded-full ring-4 ring-white" /><div className="flex flex-wrap items-baseline justify-between gap-2"><p className="font-medium text-stone-800">{action.actionTypeName}</p><span className={`text-xs font-medium ${action.status === "cancelled" ? "text-stone-400" : "text-emerald-600"}`}>{action.status === "cancelled" ? "Cancelada" : "Concluída"}</span></div><p className="mt-1 text-sm text-stone-600">Realizada em {formatDate(action.completedAt, true)}</p><p className="text-xs text-stone-400">Agendada para {formatDate(action.scheduledFor, true)}</p>{action.notes && <p className="mt-2 rounded-lg bg-stone-50 p-2 text-sm text-stone-600">{action.notes}</p>}</li>)}</ol>}{query.hasNextPage && <button disabled={query.isFetchingNextPage} onClick={() => query.fetchNextPage()} className="btn-secondary mt-4 w-full">{query.isFetchingNextPage ? "A carregar…" : "Carregar mais"}</button>}</section></>}
  </div></Modal>;
}

function TagModal({ customerIds, currentTags, bulkOperation, onClose }: { customerIds: string[]; currentTags?: CrmTag[] | undefined; bulkOperation?: "add" | "remove" | undefined; onClose: () => void }) {
  const service = useCrmWorkspace(); const qc = useQueryClient(); const { data: tags = [] } = useQuery({ queryKey: ["crm-workspace", "tags"], queryFn: service.listTags });
  const singleCustomer = currentTags !== undefined;
  const initialNames = useMemo(() => new Set(currentTags?.map((tag) => tag.name) ?? []), [currentTags]);
  const [selectedTags, setSelectedTags] = useState<Set<string>>(() => new Set(initialNames));
  const [creating, setCreating] = useState(false); const [newLabel, setNewLabel] = useState(""); const [newColor, setNewColor] = useState("#64748b");
  const mutation = useMutation({ mutationFn: service.updateTags, onSuccess: async () => { await qc.invalidateQueries({ queryKey: ["crm-workspace"] }); onClose(); } });
  const createMutation = useMutation({ mutationFn: service.createTag, onSuccess: async (created) => { setSelectedTags((current) => new Set(current).add(created.name)); setCreating(false); setNewLabel(""); await qc.invalidateQueries({ queryKey: ["crm-workspace", "tags"] }); } });
  const saveSingle = () => mutation.mutate({ customerIds, add: [...selectedTags].filter((name) => !initialNames.has(name)), remove: [...initialNames].filter((name) => !selectedTags.has(name)) });
  const saveBulk = () => mutation.mutate({ customerIds, add: bulkOperation === "add" ? [...selectedTags] : [], remove: bulkOperation === "remove" ? [...selectedTags] : [] });
  const title = singleCustomer ? `Alterar tags · ${customerIds.length} cliente` : `${bulkOperation === "remove" ? "Remover" : "Adicionar"} tags · ${customerIds.length} clientes`;
  return <Modal title={title} onClose={onClose}><div className="space-y-4">
    {!singleCustomer && <p className="text-sm text-stone-500">Selecione as tags que deseja {bulkOperation === "remove" ? "remover dos" : "adicionar aos"} clientes selecionados.</p>}
    <div className="flex max-h-64 flex-wrap gap-1 overflow-y-auto pr-1">{tags.filter((item) => item.active).length ? tags.filter((item) => item.active).map((item) => <label key={item.name} style={{ borderColor: item.color, color: item.color }} className={`inline-flex cursor-pointer items-center gap-1 rounded-full border px-2 py-0.5 text-[11px] font-medium transition ${selectedTags.has(item.name) ? "shadow-sm" : "bg-white opacity-60 hover:opacity-100"}`}><input className="sr-only" type="checkbox" checked={selectedTags.has(item.name)} onChange={() => setSelectedTags((current) => { const next = new Set(current); if (next.has(item.name)) next.delete(item.name); else next.add(item.name); return next; })} />{selectedTags.has(item.name) && <span>✓</span>}<span>{item.label}</span></label>) : <p className="w-full rounded-lg border border-dashed border-stone-200 p-4 text-center text-sm text-stone-400">Ainda não existem tags.</p>}</div>
    {(singleCustomer || bulkOperation === "add") && (!creating ? <button type="button" onClick={() => setCreating(true)} className="text-sm font-medium text-[#ED5C32] hover:underline">＋ Criar nova tag</button> : <div className="rounded-lg border border-[#F5C992]/60 bg-[#FDF8F5] p-3"><p className="mb-3 text-sm font-medium text-stone-700">Nova tag</p><div className="grid grid-cols-[1fr_48px] gap-2"><input autoFocus placeholder="Nome da tag" value={newLabel} onChange={(e) => setNewLabel(e.target.value)} className="input" /><input aria-label="Cor da tag" type="color" value={newColor} onChange={(e) => setNewColor(e.target.value)} className="h-10 w-12 rounded-md border border-stone-300 p-1" /></div>{createMutation.isError && <p className="mt-2 text-xs text-red-600">{createMutation.error.message}</p>}<div className="mt-3 flex justify-end gap-2"><button type="button" onClick={() => setCreating(false)} className="btn-secondary">Cancelar</button><button type="button" disabled={!newLabel.trim() || createMutation.isPending} onClick={() => createMutation.mutate({ label: newLabel.trim(), color: newColor })} className="btn-primary">Criar e selecionar</button></div></div>)}
    {mutation.isError && <p className="text-sm text-red-600">{mutation.error.message}</p>}
    <div className="flex justify-end gap-2"><button onClick={onClose} className="btn-secondary">Cancelar</button><button disabled={mutation.isPending || creating || (!singleCustomer && selectedTags.size === 0)} onClick={() => singleCustomer ? saveSingle() : saveBulk()} className="btn-primary">{singleCustomer ? "Guardar tags" : bulkOperation === "remove" ? "Remover tags" : "Adicionar tags"}</button></div>
  </div></Modal>;
}

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-[60] flex items-center justify-center p-4" onMouseDown={onClose}><div className="absolute inset-0 bg-black/40 backdrop-blur-sm" /><section onMouseDown={(e) => e.stopPropagation()} className="relative flex max-h-[90vh] w-full flex-col rounded-xl bg-white shadow-2xl sm:max-w-lg"><header className="flex items-center justify-between border-b border-stone-100 px-6 py-4"><h2 className="text-base font-bold text-stone-900">{title}</h2><button onClick={onClose} aria-label="Fechar" className="rounded-md p-1 text-xl leading-none text-stone-400 hover:bg-stone-100 hover:text-stone-600">×</button></header><div className="overflow-y-auto p-6">{children}</div></section></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1 block text-xs font-medium text-stone-600">{label}</span>{children}</label>; }

function Filters({ filters, setFilters }: { filters: CrmTableFilters; setFilters: React.Dispatch<React.SetStateAction<CrmTableFilters>> }) {
  const service = useCrmWorkspace(); const { data: tags = [] } = useQuery({ queryKey: ["crm-workspace", "tags"], queryFn: service.listTags });
  const { data: types = [] } = useQuery({ queryKey: ["crm-workspace", "action-types"], queryFn: service.listActionTypes });
  const selectedTags = filters.tags ?? [];
  const set = (key: keyof CrmTableFilters, value: string | undefined) => setFilters((current) => ({ ...current, [key]: value || undefined }));
  return <div><div className="flex flex-wrap items-center gap-3">
    <div className="relative min-w-64 flex-1 xl:max-w-80"><svg className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-stone-400" viewBox="0 0 20 20" fill="currentColor"><path fillRule="evenodd" d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z" clipRule="evenodd" /></svg><input value={filters.search ?? ""} onChange={(e) => set("search", e.target.value)} placeholder="Pesquisar nome, telefone ou código…" className="input pl-9" /></div>
    <select value={filters.status ?? ""} onChange={(e) => set("status", e.target.value)} className="input w-auto min-w-40"><option value="">Todos os status</option><option value="new">Novo</option><option value="recurring">Recorrente</option><option value="vip">VIP</option></select>
    <select value={filters.activity ?? ""} onChange={(e) => set("activity", e.target.value)} className="input w-auto min-w-40"><option value="">Ativos e inativos</option><option value="active">Ativos</option><option value="inactive">Inativos</option></select>
    <select value={filters.lastActionType ?? ""} onChange={(e) => set("lastActionType", e.target.value)} className="input w-auto min-w-48"><option value="">Qualquer última ação</option>{types.map((type) => <option key={type.code} value={type.code}>{type.name}</option>)}</select>
    <select value={filters.nextActionType ?? ""} onChange={(e) => set("nextActionType", e.target.value)} className="input w-auto min-w-48"><option value="">Qualquer próxima ação</option>{types.map((type) => <option key={type.code} value={type.code}>{type.name}</option>)}</select>
    <select value="" onChange={(e) => { const value = e.target.value; if (value && !selectedTags.includes(value)) setFilters((current) => ({ ...current, tags: [...selectedTags, value] })); }} className="input w-auto min-w-40"><option value="">Filtrar por tag</option>{tags.filter((tag) => tag.active && !selectedTags.includes(tag.name)).map((tag) => <option key={tag.name} value={tag.name}>{tag.label}</option>)}</select>
  </div>{selectedTags.length > 0 && <div className="mt-3 flex flex-wrap items-center gap-2"><span className="text-xs text-stone-400">Tags ({filters.tagMode === "all" ? "todas" : "qualquer"}):</span>{selectedTags.map((name) => <button key={name} onClick={() => setFilters((current) => ({ ...current, tags: selectedTags.filter((tag) => tag !== name) }))} className="rounded-full border border-stone-200 bg-white px-2.5 py-1 text-xs text-stone-600 hover:bg-stone-50">{tags.find((tag) => tag.name === name)?.label ?? name} ×</button>)}{selectedTags.length > 1 && <button onClick={() => setFilters((current) => ({ ...current, tagMode: current.tagMode === "all" ? "any" : "all" }))} className="text-xs font-medium text-[#ED5C32] hover:underline">Alternar para {filters.tagMode === "all" ? "qualquer" : "todas"}</button>}</div>}</div>;
}

function CustomerRow({ item, selected, toggle, handleNextAction, showHistory, editTags }: { item: CrmTableItem; selected: boolean; toggle: () => void; handleNextAction: () => void; showHistory: () => void; editTags: () => void }) {
  const [copied, setCopied] = useState(false); const copy = async () => { if (!item.phone) return; await navigator.clipboard.writeText(item.phone); setCopied(true); window.setTimeout(() => setCopied(false), 1200); };
  return <tr className={`group align-top transition-colors hover:bg-[#FDF8F5] ${selected ? "bg-[#ED5C32]/5" : ""}`}>
    <td className="sticky left-0 z-10 bg-inherit px-4 py-3"><input aria-label={`Selecionar ${item.fullName}`} type="checkbox" checked={selected} onChange={toggle} className="h-3.5 w-3.5 rounded border-stone-300 text-[#ED5C32] focus:ring-[#ED5C32]" /></td>
    <td className="px-3 py-3"><StatusBadges item={item} /></td>
    <td className="sticky left-12 z-10 min-w-48 bg-inherit px-3 py-3"><Link to={`/crm/customers/${item.id}`} className="font-semibold text-stone-900 hover:text-[#ED5C32]">{item.fullName}</Link><div className="mt-0.5 text-xs text-stone-400">{item.id}</div></td>
    <td className="px-3 py-3"><button disabled={!item.phone} onClick={copy} title="Copiar telefone" className="whitespace-nowrap text-sm text-stone-500 underline decoration-stone-200/70 underline-offset-4 transition-colors hover:text-[#ED5C32] hover:decoration-[#ED5C32] disabled:text-stone-300 disabled:no-underline">{copied ? "Copiado ✓" : item.phone ?? "—"}</button></td>
    <td className="px-3 py-3 text-center font-semibold text-stone-800">{item.orderCount}</td><td className="whitespace-nowrap px-3 py-3 text-sm text-stone-700">{formatDate(item.lastOrderDate)}</td>
    <td className="min-w-44 px-3 py-3"><button onClick={showHistory} title="Ver histórico de ações" className="text-left"><div className="text-sm text-stone-500 underline decoration-stone-200/70 underline-offset-4 transition-colors hover:text-[#ED5C32] hover:decoration-[#ED5C32]">{item.lastAction?.typeName ?? "Ver histórico"}</div><div className="mt-0.5 text-xs text-stone-400">{item.lastAction ? formatDate(item.lastAction.completedAt, true) : "Sem ações concluídas"}</div></button></td>
    <td className="min-w-52 px-3 py-3"><button onClick={handleNextAction} className="text-left"><div className="text-sm text-stone-500 underline decoration-stone-200/70 underline-offset-4 transition-colors hover:text-[#ED5C32] hover:decoration-[#ED5C32]">{item.nextAction?.typeName ?? "+ Agendar ação"}</div>{item.nextAction?.scriptCode && <div className="text-xs text-stone-400">{item.nextAction.scriptCode}</div>}{item.nextAction && <div className={`mt-0.5 text-xs ${item.followUpDate && item.followUpDate.slice(0, 10) < new Date().toISOString().slice(0, 10) ? "font-medium text-red-600" : "text-stone-400"}`}>{formatDate(item.followUpDate, true)}</div>}</button></td>
    <td className="min-w-44 px-3 py-3"><button onClick={editTags} title="Adicionar ou remover tags" className="text-left"><div className="flex max-w-56 flex-wrap gap-1">{item.tags.length ? item.tags.map((tag) => <span key={tag.name} style={{ borderColor: tag.color, color: tag.color }} className="rounded-full border px-2 py-0.5 text-[11px] font-medium">{tag.label}</span>) : <span className="text-sm text-stone-400 hover:text-[#ED5C32]">+ Adicionar tag</span>}</div></button></td>
    <td className="min-w-40 px-3 py-3"><div className="text-sm text-stone-700">{item.lastScript?.name ?? "—"}</div><div className="mt-0.5 text-xs text-stone-400">{formatDate(item.lastScript?.sentAt ?? null)}</div></td>
  </tr>;
}

export function CrmCustomersView() {
  const service = useCrmWorkspace(); const [filters, setFilters] = useState<CrmTableFilters>({ tagMode: "any", page: 1, pageSize: 10 });
  const [selected, setSelected] = useState<Set<string>>(new Set()); const [actionIds, setActionIds] = useState<string[] | null>(null); const [completionTargets, setCompletionTargets] = useState<CrmTableItem[] | null>(null); const [historyTarget, setHistoryTarget] = useState<CrmTableItem | null>(null); const [tagTarget, setTagTarget] = useState<{ customerIds: string[]; currentTags?: CrmTag[] | undefined; bulkOperation?: "add" | "remove" | undefined } | null>(null);
  const key = useMemo(() => ["crm-workspace", "customers", filters] as const, [filters]);
  const query = useQuery({ queryKey: key, queryFn: () => service.listCustomers(filters), placeholderData: (previous) => previous }); const items = query.data?.items ?? [];
  const ids = [...selected]; const selectedWithPendingAction = items.filter((item) => selected.has(item.id) && item.nextAction !== null); const allSelected = items.length > 0 && items.every((item) => selected.has(item.id));
  const cycleSort = (sortBy: "customerId" | "orderCount" | "lastOrderDate", firstDirection: "asc" | "desc") => {
    setSelected(new Set());
    setFilters((current) => {
      if (current.sortBy !== sortBy) return { ...current, sortBy, sortDirection: firstDirection, page: 1 };
      if (current.sortDirection === firstDirection) return { ...current, sortDirection: firstDirection === "asc" ? "desc" : "asc", page: 1 };
      return { ...current, sortBy: undefined, sortDirection: undefined, page: 1 };
    });
  };
  const updateFilters: React.Dispatch<React.SetStateAction<CrmTableFilters>> = (next) => {
    setSelected(new Set());
    setFilters((current) => ({ ...(typeof next === "function" ? next(current) : next), page: 1 }));
  };
  const page = query.data?.page ?? filters.page ?? 1; const pageSize = query.data?.pageSize ?? filters.pageSize ?? 10;
  const total = query.data?.total ?? 0; const totalPages = Math.max(1, Math.ceil(total / pageSize));
  const visiblePages = Array.from({ length: totalPages }, (_, index) => index + 1).filter((number) => totalPages <= 7 || number === 1 || number === totalPages || Math.abs(number - page) <= 1);
  return <div className="min-h-screen bg-[#FAF6F3]">
    <div className="border-b border-[#F5C992]/40 bg-white px-4 py-4 sm:px-6"><h1 className="text-xl font-bold text-stone-900">Clientes</h1><p className="mt-0.5 text-sm text-stone-500">Gestão de clientes, ações de acompanhamento e tags</p></div>
    <div className="space-y-4 p-4 sm:p-6">
      <Filters filters={filters} setFilters={updateFilters} />
      <div className="overflow-hidden rounded-xl border border-[#F5C992]/40 bg-white">
        {selected.size > 0 && <div className="flex flex-wrap items-center gap-2 border-b border-[#F5C992]/40 bg-[#ED5C32]/5 px-4 py-2.5"><strong className="mr-1 text-xs font-medium text-stone-700">{selected.size} selecionado(s)</strong><button onClick={() => setActionIds(ids)} className="btn-primary py-1.5 text-xs">+ Agendar ação</button><button disabled={selectedWithPendingAction.length === 0} onClick={() => setCompletionTargets(selectedWithPendingAction)} className="btn-secondary py-1.5 text-xs">Concluir próxima ação{selectedWithPendingAction.length > 0 ? ` (${selectedWithPendingAction.length})` : ""}</button><button onClick={() => setTagTarget({ customerIds: ids, bulkOperation: "add" })} className="btn-secondary py-1.5 text-xs">Adicionar tags</button><button onClick={() => setTagTarget({ customerIds: ids, bulkOperation: "remove" })} className="btn-secondary py-1.5 text-xs">Remover tags</button><button onClick={() => setSelected(new Set())} className="ml-auto text-xs text-stone-400 hover:text-stone-600">Cancelar</button></div>}
        {query.isLoading ? <div className="py-16 text-center text-sm text-stone-400">A carregar clientes…</div> : query.isError ? <div className="p-8 text-center text-sm text-red-600">{query.error.message}</div> : items.length === 0 ? <div className="py-16 text-center text-sm text-stone-400">Nenhum cliente corresponde aos filtros.</div> : <><div className="hidden overflow-x-auto lg:block"><table className="min-w-[1320px] w-full border-collapse text-left text-sm"><thead className="sticky top-0 z-20 border-b border-[#F5C992]/40 bg-stone-50/60"><tr><th className="sticky left-0 z-30 w-12 bg-stone-50/95 px-4 py-3"><input aria-label="Selecionar todos os clientes desta página" type="checkbox" checked={allSelected} onChange={() => setSelected(allSelected ? new Set() : new Set(items.map((item) => item.id)))} className="h-3.5 w-3.5 rounded border-stone-300 text-[#ED5C32] focus:ring-[#ED5C32]" /></th><th className="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wide text-stone-500">Status</th><SortableHeader label="Cliente" sticky active={filters.sortBy === "customerId"} direction={filters.sortDirection} onClick={() => cycleSort("customerId", "asc")} /><th className="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wide text-stone-500">Telefone</th><SortableHeader label="Pedidos" active={filters.sortBy === "orderCount"} direction={filters.sortDirection} onClick={() => cycleSort("orderCount", "desc")} /><SortableHeader label="Último pedido" active={filters.sortBy === "lastOrderDate"} direction={filters.sortDirection} onClick={() => cycleSort("lastOrderDate", "desc")} /><th className="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wide text-stone-500">Última ação</th><th className="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wide text-stone-500">Próxima ação</th><th className="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wide text-stone-500">Tags</th><th className="px-3 py-3 text-left text-xs font-semibold uppercase tracking-wide text-stone-500">Último script (Temporário)</th></tr></thead><tbody className="divide-y divide-[#F5C992]/30">{items.map((item) => <CustomerRow key={item.id} item={item} selected={selected.has(item.id)} toggle={() => setSelected((current) => { const next = new Set(current); if (next.has(item.id)) next.delete(item.id); else next.add(item.id); return next; })} handleNextAction={() => item.nextAction ? setCompletionTargets([item]) : setActionIds([item.id])} showHistory={() => setHistoryTarget(item)} editTags={() => setTagTarget({ customerIds: [item.id], currentTags: item.tags })} />)}</tbody></table></div>
        <div className="divide-y divide-[#F5C992]/30 lg:hidden">{items.map((item) => <article key={item.id} className={`p-4 transition-colors hover:bg-[#FDF8F5] ${selected.has(item.id) ? "bg-[#ED5C32]/5" : ""}`}><div className="flex items-start gap-3"><input type="checkbox" checked={selected.has(item.id)} onChange={() => setSelected((current) => { const next = new Set(current); if (next.has(item.id)) next.delete(item.id); else next.add(item.id); return next; })} className="mt-1 h-3.5 w-3.5 rounded border-stone-300 text-[#ED5C32] focus:ring-[#ED5C32]" /><div className="min-w-0 flex-1"><Link to={`/crm/customers/${item.id}`} className="font-semibold text-stone-900 hover:text-[#ED5C32]">{item.fullName}</Link><div className="mt-1"><StatusBadges item={item} /></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-stone-500"><span>{item.orderCount} pedidos</span><span>Último: {formatDate(item.lastOrderDate)}</span><button onClick={() => setHistoryTarget(item)} className="col-span-2 text-left underline decoration-stone-200/70 underline-offset-4 transition-colors hover:text-[#ED5C32] hover:decoration-[#ED5C32]">Histórico: {item.lastAction?.typeName ?? "Ver ações"}</button><button onClick={() => item.nextAction ? setCompletionTargets([item]) : setActionIds([item.id])} className="col-span-2 text-left underline decoration-stone-200/70 underline-offset-4 transition-colors hover:text-[#ED5C32] hover:decoration-[#ED5C32]">Próxima: {item.nextAction?.typeName ?? "+ Agendar ação"}{item.nextAction ? ` · ${formatDate(item.followUpDate)}` : ""}</button><button onClick={() => setTagTarget({ customerIds: [item.id], currentTags: item.tags })} className="col-span-2 text-left hover:text-[#ED5C32]">Tags: {item.tags.length ? item.tags.map((tag) => tag.label).join(", ") : "+ Adicionar tag"}</button></div></div></div></article>)}</div></>}
        {query.data && total > 0 && <div className="flex flex-col gap-3 border-t border-[#F5C992]/40 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap items-center gap-2 text-xs text-stone-500"><span>Mostrar</span><select value={pageSize} onChange={(event) => { setSelected(new Set()); setFilters((current) => ({ ...current, page: 1, pageSize: Number(event.target.value) as 10 | 25 | 50 | 100 })); }} className="rounded-md border border-stone-200 bg-white px-2 py-1.5 text-xs text-stone-700 focus:border-[#ED5C32] focus:outline-none"><option value={10}>10</option><option value={25}>25</option><option value={50}>50</option><option value={100}>100</option></select><span>por página · Mostrando {Math.min((page - 1) * pageSize + 1, total)} a {Math.min(page * pageSize, total)} de {total} clientes</span></div><div className="flex items-center gap-1"><button aria-label="Página anterior" disabled={page <= 1 || query.isFetching} onClick={() => { setSelected(new Set()); setFilters((current) => ({ ...current, page: Math.max(1, page - 1) })); }} className="flex h-7 w-7 items-center justify-center rounded border border-stone-200 text-stone-500 hover:bg-stone-50 disabled:opacity-40">‹</button>{visiblePages.map((number, index) => <span key={number} className="contents">{index > 0 && number - visiblePages[index - 1]! > 1 && <span className="flex h-7 w-5 items-center justify-center text-xs text-stone-400">…</span>}<button onClick={() => { setSelected(new Set()); setFilters((current) => ({ ...current, page: number })); }} className={`flex h-7 w-7 items-center justify-center rounded border text-xs font-medium ${number === page ? "border-[#ED5C32] bg-[#ED5C32]/10 text-[#ED5C32]" : "border-stone-200 text-stone-500 hover:bg-stone-50"}`}>{number}</button></span>)}<button aria-label="Página seguinte" disabled={page >= totalPages || query.isFetching} onClick={() => { setSelected(new Set()); setFilters((current) => ({ ...current, page: Math.min(totalPages, page + 1) })); }} className="flex h-7 w-7 items-center justify-center rounded border border-stone-200 text-stone-500 hover:bg-stone-50 disabled:opacity-40">›</button></div></div>}
      </div>
    </div>
    {actionIds && <ActionModal customerIds={actionIds} onClose={() => setActionIds(null)} />}{completionTargets && <CompleteActionModal items={completionTargets} onClose={() => { setCompletionTargets(null); setSelected(new Set()); }} />}{historyTarget && <ActionHistoryModal item={historyTarget} onClose={() => setHistoryTarget(null)} onSchedule={() => { const id = historyTarget.id; setHistoryTarget(null); setActionIds([id]); }} />}{tagTarget && <TagModal customerIds={tagTarget.customerIds} currentTags={tagTarget.currentTags} bulkOperation={tagTarget.bulkOperation} onClose={() => setTagTarget(null)} />}
  </div>;
}
